image: registry.gitlab.tugraz.at/dbp/relay/bundle-install-test/main:v1

before_script:
  - 'git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.tugraz.at/".insteadOf "git@gitlab.tugraz.at:"'
  - 'git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.tugraz.at/".insteadOf "https://gitlab.tugraz.at/"'

variables:
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/_composer_cache"

cache:
  key: ${CI_PROJECT_PATH}
  paths:
    - _composer_cache

stages:
  - test

.bundle_install_defaults: &bundle_install_defaults
  script:
    - sudo update-alternatives --set php "/usr/bin/${PHP}"
    - composer --version -vvv
    - ./test.sh

bundle-install-php7.4:
  stage: test
  variables:
    PHP: "php7.4"
  <<: *bundle_install_defaults

bundle-install-php8.0:
  stage: test
  variables:
    PHP: "php8.0"
  <<: *bundle_install_defaults

bundle-install-php8.1:
  stage: test
  variables:
    PHP: "php8.1"
  <<: *bundle_install_defaults
